import { createClient } from "@/lib/supabase/server";
import type { AuditRow, AuditRecommendationRow, PublicAudit, PublicAuditSafe } from "@/types/database";
import type { AuditEngineResult, WorkspaceMetrics } from "@/types/audit-engine";

// ── Types ────────────────────────────────────────────────────────────────────

export interface SaveAuditInput {
  title: string;
  organizationId: string;
  workspaces: WorkspaceMetrics[];
  result: AuditEngineResult;
  aiSummary?: string;
  userId?: string;
}

export interface SaveAuditOutput {
  auditId: string;
  shareId: string;
}

// ── Save pipeline ─────────────────────────────────────────────────────────────

export async function saveAuditReport(input: SaveAuditInput): Promise<SaveAuditOutput> {
  const supabase = await createClient();

  // Derive aggregate metrics from workspaces for the audit row
  const avgUtilization =
    input.workspaces.reduce((s, w) => s + w.utilizationRate, 0) / input.workspaces.length;

  // 1. Insert audit row — share_id is generated by Postgres uuid_generate_v4() default
  const { data: audit, error: auditError } = await supabase
    .from("audits")
    .insert({
      organization_id: input.organizationId,
      title: input.title,
      provider: input.result.providersScanned.join(", "),
      total_monthly_spend: input.result.totalCurrentSpend,
      total_annual_spend: input.result.totalCurrentSpend * 12,
      estimated_monthly_savings: input.result.totalMonthlySavings,
      estimated_annual_savings: input.result.totalAnnualSavings,
      utilization_rate: Math.round(avgUtilization * 100) / 100,
      optimization_score: input.result.optimizationScore,
      ai_summary: input.aiSummary ?? null,
      is_public: true,
      created_by: input.userId ?? "00000000-0000-0000-0000-000000000000",
    })
    .select("id, share_id")
    .single();

  if (auditError) {
    console.error("Audit insert error:", auditError);
    throw auditError;
  }

  // 2. Bulk-insert recommendations tied to the new audit
  const recommendationRows: Omit<AuditRecommendationRow, "id" | "created_at">[] =
    input.result.recommendations.map((r) => ({
      audit_id: audit.id,
      provider: r.provider,
      title: r.title,
      recommendation: r.recommendation,
      reason: r.reason,
      confidence_score: r.confidenceScore,
      priority: r.priority,
      monthly_savings: r.monthlySavings,
      annual_savings: r.annualSavings,
      affected_users: r.affectedUsers ?? 0,
      rule_id: r.ruleId,
    }));

  const { error: recsError } = await supabase
    .from("audit_recommendations")
    .insert(recommendationRows);

  if (recsError) {
    // Roll back the audit row so we don't leave orphaned records
    await supabase.from("audits").delete().eq("id", audit.id);
    throw recsError;
  }

  return { auditId: audit.id, shareId: audit.share_id };
}

// ── Fetch helpers ─────────────────────────────────────────────────────────────

export async function getMyAudits(): Promise<AuditRow[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("audits")
    .select("*")
    .order("created_at", { ascending: false });
  if (error) throw error;
  return data;
}

export async function getAuditById(id: string): Promise<PublicAudit> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("audits")
    .select("*, audit_recommendations(*)")
    .eq("id", id)
    .single();
  if (error) throw error;
  return data as PublicAudit;
}

// Fetch by share_id for /results/[id] route (same sanitizer, URL-friendly lookup)
export async function getPublicAuditById(id: string): Promise<PublicAuditSafe> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("audits")
    .select("*, audit_recommendations(*)")
    .eq("share_id", id)
    .eq("is_public", true)
    .single();
  if (error) throw error;
  return stripSensitiveData(data as PublicAudit);
}

// Returns the sanitized public shape — no org/user IDs, no internal fields
export async function getPublicAudit(shareId: string): Promise<PublicAuditSafe> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("audits")
    .select("*, audit_recommendations(*)")
    .eq("share_id", shareId)
    .eq("is_public", true)
    .single();
  if (error) throw error;
  return stripSensitiveData(data as PublicAudit);
}

// ── Publish toggle ────────────────────────────────────────────────────────────

export async function setAuditPublic(auditId: string, isPublic: boolean): Promise<void> {
  const supabase = await createClient();
  const { error } = await supabase
    .from("audits")
    .update({ is_public: isPublic })
    .eq("id", auditId);
  if (error) throw error;
}

// ── Sanitizer ─────────────────────────────────────────────────────────────────

export function stripSensitiveData(audit: PublicAudit): PublicAuditSafe {
  return {
    title: audit.title,
    share_id: audit.share_id,
    created_at: audit.created_at,
    estimated_monthly_savings: audit.estimated_monthly_savings,
    estimated_annual_savings: audit.estimated_annual_savings,
    optimization_score: audit.optimization_score,
    ai_summary: audit.ai_summary,
    recommendations: audit.audit_recommendations.map((r) => ({
      id: r.id,
      provider: r.provider,
      title: r.title,
      recommendation: r.recommendation,
      reason: r.reason,
      priority: r.priority,
      monthly_savings: r.monthly_savings,
      annual_savings: r.annual_savings,
      affected_users: r.affected_users,
      // rule_id, confidence_score, audit_id intentionally omitted
    })),
  };
}
